### ISSUE TITLE
Azure Functions CLI Tooling Errors with latest .NET 6 Preview installed

### ISSUE THREAD

**Issue by WestDiscGolf** [Azure/azure-functions-templates#1076] opened 2021-08-03 14:38 UTC
When using the Azure Function CLI, unable to create a new C# based Azure Function through `func new` functionality.

## .NET SDKs installed

C:\Temp\azure-issues> dotnet --list-sdks
2.2.401 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
3.1.406 [C:\Program Files\dotnet\sdk]
5.0.103 [C:\Program Files\dotnet\sdk]
5.0.302 [C:\Program Files\dotnet\sdk]
5.0.400-preview.21328.4 [C:\Program Files\dotnet\sdk]
6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
C:\Temp\azure-issues>

## Azure Functions Core Tools installed

C:\Temp\azure-issues> func

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools
Core Tools Version:       3.0.3568 Commit hash: e30a0ede85fd498199c28ad699ab2548593f759b  (64-bit)
Function Runtime Version: 3.0.15828.0

## Steps to reproduce

1. create directory
2. do into directory
3. `func init` to create C# function app
4. `func new` to create C# Http Trigger function
5. Select HttpTrigger and name the function

## Expected results
New function is created

## Actual results
Template error.

C:\Temp\azure-issues> func new
Use the up/down arrow keys to select a template:Function name: TestForIssue
TestForIssue
No templates found matching: 'HttpTrigger'.
To list installed templates, run 'dotnet new --list'.
To search for the templates on NuGet.org, run 'dotnet new HttpTrigger --search'.

Error creating function

## Work Around

Add in global json file

More info - https://adamstorr.azurewebsites.net/blog/azure-functions-cli-failing-after-preview-install

Logged under guidance from Anthony Chu - https://twitter.com/nthonyChu/status/1422565903284129793

**Comment by WestDiscGolf** [comment] 2021-08-12 07:34
Updated to the latest preview, both .net 6 and core functions v4, and still experiencing the same issue.

C:\Temp\azure-issues> func new
Use the up/down arrow keys to select a template:Function name: TestForIssue2
TestForIssue2
No templates found matching: 'HttpTrigger'.

To list installed templates, run:
   dotnet new --list
To search for the templates on NuGet.org, run:
   dotnet new HttpTrigger --search


Error creating function
C:\Temp\azure-issues>

**Comment by WestDiscGolf** [comment] 2021-08-12 07:38
Adding the global json file work around posted in the original issue body I linked to on my blog doesn't work for the v6 version either.

C:\Temp\azure-issues> dotnet new globaljson
The template "global.json file" was created successfully.
C:\Temp\azure-issues> explorer .
C:\Temp\azure-issues> func new
Use the up/down arrow keys to select a template:Function name: Test
Test
No templates found matching: 'HttpTrigger'.

To list installed templates, run:
   dotnet new --list
To search for the templates on NuGet.org, run:
   dotnet new HttpTrigger --search


Error creating function

Global Json Content
```
{
  "sdk": {
    "version": "6.0.100-preview.7.21379.14"
  }
}
```

**Comment by WestDiscGolf** [comment] 2021-08-12 07:57
Doesn't work on a linux container in Github codespaces either.

```
9. CosmosDBTrigger
Choose option: 2
Function name: Message
Message
No templates found matching: 'HttpTrigger'.

To list installed templates, run:
   dotnet new --list
To search for the templates on NuGet.org, run:
   dotnet new HttpTrigger --search


Error creating function
```

**Comment by WestDiscGolf** [comment] 2021-08-12 07:57
@anthonychu

**Comment by anthonychu** [comment] 2021-08-17 03:58
@fabiocav can you please take a look?

**Comment by PeterAronZentai** [comment] 2021-09-07 03:31
Folks, any update on this?

**Comment by anthonychu** [comment] 2021-09-13 21:43
A new version of Core Tools V4 with a fix has been published. This is currently available on npm: `npm install -g azure-functions-core-tools@4`.

**Comment by brettsam** [comment] 2021-09-13 21:48
To link things together -- this was fixed in https://github.com/Azure/azure-functions-core-tools/pull/2693. Root cause was https://github.com/dotnet/templating/issues/3779 and we had to switch to using shortnames for templates internally.

**Closed by brettsam** 2021-09-13 21:48 UTC
Labels: Needs: Triage (functions)
