### ISSUE TITLE
When Creating New Function from "Add -> New Function" the Namespace is not escaped properly

### ISSUE THREAD

**Issue by skyhoshi** [Azure/azure-functions-templates#487] opened 2017-07-04 12:53 UTC
when creating a new function the namespace if the function project has spaces is not escaped properly

Each new function I create in the project I have to correct by adding the _ to the namespace of the code file generated. 

after reviewing the project file, the stored Namespace in the properties is not properly escaped. after changing that to the properly escaped Namespace Name, the newly created Functions were fixed(properly escaped) as well. 

Reproduction: 
1. Create a project with a name that has multiple spaces within it.
2. Attempt to create a new function using the function template from Add -> New Item
3. Review the namespace in the file. 
4. Review the namespace in the project's properties.

**Comment by seancpeters** [comment] 2017-07-14 01:13
If you can point me at an example template that has this problem, I can take a look into how to fix this issue.

**Comment by skyhoshi** [comment] 2017-07-14 01:34
it seems to be any Template that I use creates the problem because the issue is with the Project's namespace. 

I tried, the Timed Trigger (TimedTriggerCSharp) and the Blog Trigger BlogTriggerCSharp. but any of the C#'s have an issue with it.

I've created several Projects, and several functions, and each class is correctly escaped but the Project level namespace is not.

I can send you the project i'm working with (just a new blank project to start, then upon adding the function the problem is shown.) 

Hope this helps

**Comment by seancpeters** [comment] 2017-07-14 01:38
Please do send it, I think I know what the problem is, but would like to see a specific example to make sure.

**Comment by skyhoshi** [comment] 2017-07-14 01:48
[My Default Spaced Function Project Collection.zip](https://github.com/Azure/azure-webjobs-sdk-templates/files/1147107/My.Default.Spaced.Function.Project.Collection.zip)
I made a new solution of the problem, created one project with two functions. when you open one of the functions the problems rather clear. 
it doesn't matter what function type I use.

**Comment by skyhoshi** [comment] 2017-07-14 01:49
also, when I go into the project properties. you can see the Namespace is not Escaped. (that's how I fixed the issue for new Functions) sorry I left that out. i'm kinda new to this.

**Comment by seancpeters** [comment] 2017-07-17 21:44
Looking further into this, it's a duplicate of https://github.com/dotnet/project-system/issues/2016

The namespace to use comes from VS and is expected to be valid. But we can setup some cleansing in the template configuration. This will be easiest after some in-flight changes in the dotnet/templating repo get merged - specifically: https://github.com/dotnet/templating/pull/867

In the mean time, here are some best-practice-type change suggestions for the TimerTrigger template (and analogous changes to other templates with similar issues):

Remove the symbol "FunctionName" from template.json. In run.cs change 
`[FunctionName("FunctionNameValue")]` 
to 
`[FunctionName("TimerTriggerCSharp")]` 
Since "TimerTriggerCSharp" is the value of sourceName, the name provided to the template from VS will be used to replace all instances of "TimerTriggerCSharp". The sourceName gets some special processing to attempt to cleanse the value to be appropriate for class names and namespaces.
It would probably be best to also change the filename `run.cs` to TimerTriggerCSharp. 


Note: The templating PR mentioned above exposes the "special processing" for sourceName, so that other parameters can be configured to easily leverage that processing.

**Comment by soninaren** [comment] 2017-07-17 22:02
Thanks for the insight sean, I will change the
`[FunctionName("FunctionNameValue")]`
to
`[FunctionName("TimerTriggerCSharp")]`

**Comment by soninaren** [comment] 2017-07-17 22:05
I had a follow up question regarding changing file name run.cs. The template build depends on the file name being run.cs. Is there a scenario analogous to this issue that could affect run.cs as well?. Otherwise for now i would like to keep it as run.cs until i update the build.

**Comment by seancpeters** [comment] 2017-07-17 22:12
The reasons to make the name of the file dynamic would be:
- Consistency between the class anme & filename (standard coding convention)
- Avoiding filename clashes if someone creates the same template twice in the same directory.

Beyond those concerns, it should be fine as-is, so I'd say it's not a needs-to-happen-now issue.

**Comment by seancpeters** [comment] 2017-07-20 18:31
Following up on the reasons to make the file name dynamic, when the template ships in VS, the name will need to be dynamic & agree with the class name - it's a requirement for item templates in VS.

**Comment by justcla** [comment] 2017-12-14 00:25
I had the same issue when creating a Timer Trigger when my Functions project name included a hyphen.

![image](https://user-images.githubusercontent.com/17131343/33969444-3fa34532-e022-11e7-85f0-59559b49fbf6.png)

**Comment by soninaren** [comment] 2018-07-24 01:09
The code fix has been checked in.  New projects files should be automatically escape the namespace properly. For existing projects please add the following to the csproj file

```XML
<RootNamespace>Expected_Namespace</RootNamespace>
```

**Closed by soninaren** 2018-07-24 01:09 UTC
Labels: bug
